camel.main.name = camelbee-standalone-sample

# embedded platform-http server (camel-platform-http-main, brought by the starter)
camel.server.enabled = true
camel.server.host = 0.0.0.0
camel.server.port = 8080

# CamelBee
camelbee.context-enabled = true
camelbee.notifier-enabled = true
camelbee.tracer-enabled = true
